/* ============================================================
   DOCUMENT INTELLIGENCE ENGINE — Content Seeder
   Phase 9: Content Seeder

   Populates LumioState.lessons[id] for each lesson in a course
   that was generated by the Document Intelligence Engine.

   Called from createCourseFromWizard() in wizard.js immediately
   after the empty lesson arrays are seeded, when:
     LumioState.wizard.source === 'document-intelligence'

   The seeder iterates course.lessons[] in parallel with
   blueprint.lessons[] (same index). Each blueprint lesson
   carries _blockSuggestions[] (added by DocIntelWizardBuilder)
   which DocIntelBlockBuilder converts to Lumio block objects.

   Only lessons with at least one block suggestion are populated.
   Empty lessons (no suggestions) remain as [] — this preserves
   the existing Builder empty-state UX for those lessons.

   Dependencies (global IIFE modules, loaded before this file):
     - DocIntelBlockBuilder  (seeder/blockBuilder.js)
     - LumioState            (app.js)

   No UI. No side effects beyond LumioState.lessons.
   ============================================================ */

const DocIntelContentSeeder = (() => {

  /**
   * Seeds LumioState.lessons[id] for every lesson in a
   * DocIntel-generated course using pre-computed block suggestions.
   *
   * @param {Array} courseLessons    course.lessons[] — each has { id, title, … }
   * @param {Array} blueprintLessons blueprint.lessons[] — each has { _blockSuggestions[] }
   * @param {Array} [objectives]     wizard.objectives[] — each has { verb, text }
   */
  function seed(courseLessons, blueprintLessons, objectives) {
    if (!Array.isArray(courseLessons) || !Array.isArray(blueprintLessons)) return;

    courseLessons.forEach((courseLesson, i) => {
      const bpLesson = blueprintLessons[i];
      if (!bpLesson || !Array.isArray(bpLesson._blockSuggestions) || bpLesson._blockSuggestions.length === 0) {
        return; // leave LumioState.lessons[courseLesson.id] as []
      }

      const objective = Array.isArray(objectives) ? (objectives[bpLesson.objectiveIndex] || null) : null;
      const composed  = DocIntelLessonComposer.compose(bpLesson._blockSuggestions, courseLesson.title, objective);

      const blocks = composed
        .map(s => DocIntelBlockBuilder.build(s))
        .filter(Boolean);

      if (blocks.length > 0) {
        LumioState.lessons[courseLesson.id] = blocks;
      }
    });
  }

  return Object.freeze({ seed });

})();
