-- Migration number: 0002    2026-07-05
--
-- Phase 1 Cloud Infrastructure Sprint — Content Schema.
-- Creates all remaining application tables: projects, courses, lessons,
-- lesson_objectives, lesson_objective_links, assets, reviews,
-- notifications, and audit_log.
--
-- Depends on: 0001_create_core_tables.sql (users, workspaces,
-- workspace_members, sessions, password_resets must exist first).
--
-- Design principles:
--   • All IDs are TEXT (ULIDs/UUIDs generated by the application layer,
--     same pattern established in 0001).
--   • All timestamps are INTEGER (Unix epoch milliseconds), consistent
--     with 0001 and with the existing LumioState JS model.
--   • Foreign keys are ON DELETE CASCADE for child data (losing a workspace
--     removes its projects; losing a project removes its courses/lessons) and
--     ON DELETE RESTRICT for ownership references that must be transferred
--     before deletion can proceed.
--   • Soft-delete (deleted_at INTEGER NULL) on the three highest-value
--     resource types: projects, courses, assets. Lessons and lower are
--     cascade-deleted with their parents.
--   • Workspace isolation: every content table carries workspace_id so
--     every query can be scoped without a multi-table join. This closes the
--     architectural gap identified in the Phase 1 audit (G1 — projects are
--     not workspace-namespaced in the prototype).
--   • status columns use TEXT with a CHECK constraint where the allowed
--     values are known and stable; left unconstrained where future sprints
--     are likely to add values.

PRAGMA foreign_keys = ON;


-- ===========================================================================
-- projects
-- ===========================================================================
-- A project is the top-level authoring unit in Lumio — a Course or a
-- Microlearning. It is the entry in the Projects list, the thing that goes
-- through the review workflow, and the container for one Course record.
--
-- workspace_id gives every query the workspace scope it needs without a join.
-- owner_id is the user who created it; it never changes except via an
-- explicit ownership-transfer operation (not yet implemented but reserved).
CREATE TABLE projects (
  id              TEXT PRIMARY KEY,
  workspace_id    TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  owner_id        TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  title           TEXT NOT NULL,
  type            TEXT NOT NULL
                    CHECK (type IN ('Course', 'Microlearning')),
  -- Project lifecycle: draft → in_review → approved → published → archived.
  -- Rejection reverts to draft (or a first-class 'rejected' status per the
  -- existing governance sprint work — see app.js PROJECT_STATUS_TRANSITIONS).
  status          TEXT NOT NULL DEFAULT 'draft'
                    CHECK (status IN ('draft', 'in_review', 'rejected',
                                      'approved', 'published', 'archived')),
  -- health is a computed integer 0–100 shown on project cards. Stored here
  -- so the Projects list can sort/filter by it without re-computing it per
  -- request. Updated whenever the course structure changes.
  health          INTEGER NOT NULL DEFAULT 0
                    CHECK (health BETWEEN 0 AND 100),
  -- folder_id is NULL when the project is in "All Projects" (no folder).
  folder_id       TEXT REFERENCES folders(id) ON DELETE SET NULL,
  -- Sharing model: scope is NULL (private), 'team' (all workspace members),
  -- or will gain 'external' in a future sprint. permission gates edit vs view.
  shared_scope      TEXT CHECK (shared_scope IN ('team') OR shared_scope IS NULL),
  shared_permission TEXT NOT NULL DEFAULT 'view'
                       CHECK (shared_permission IN ('view', 'edit')),
  last_accessed_at  INTEGER,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL,
  deleted_at        INTEGER
);

CREATE INDEX idx_projects_workspace   ON projects (workspace_id);
CREATE INDEX idx_projects_owner       ON projects (owner_id);
CREATE INDEX idx_projects_workspace_status ON projects (workspace_id, status)
  WHERE deleted_at IS NULL;


-- ===========================================================================
-- project_shares
-- ===========================================================================
-- Explicit per-user sharing grants (when shared_scope IS NULL on the project
-- but specific users should still have access). Mirrors the prototype's
-- project.sharedWith array as a proper join table.
CREATE TABLE project_shares (
  project_id  TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  permission  TEXT NOT NULL DEFAULT 'view'
                CHECK (permission IN ('view', 'edit')),
  granted_at  INTEGER NOT NULL,
  PRIMARY KEY (project_id, user_id)
);

CREATE INDEX idx_project_shares_user ON project_shares (user_id);


-- ===========================================================================
-- folders
-- ===========================================================================
-- Project organisational groups, scoped to a workspace.
-- Projects reference folders via folder_id (nullable FK with SET NULL).
-- Declared before projects so the FK can reference it; the projects table
-- references folders(id) above — circular order resolved by declaring
-- folders first and adding the project FK as a deferred constraint below.
--
-- NOTE: folders is declared here (after projects in the logical design)
-- because SQLite resolves FKs at DML time, not DDL time — the CREATE TABLE
-- order just needs folders to exist before any INSERT, not before the
-- referencing table's CREATE TABLE. The projects.folder_id FK is therefore
-- valid even though projects was declared first in this file.
CREATE TABLE folders (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  color         TEXT NOT NULL DEFAULT 'purple',
  icon          TEXT,
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL
);

CREATE INDEX idx_folders_workspace ON folders (workspace_id);


-- ===========================================================================
-- courses
-- ===========================================================================
-- One-to-one with projects (a project always has exactly one course).
-- Holds the instructional design metadata: objectives, learner outcomes,
-- theme, landing layout, hero image settings, duration estimate.
-- Lesson structure is in the lessons table; lesson content is in
-- lesson_blocks (JSON column) to avoid an explosion of rows for what is
-- fundamentally a document-shaped data structure.
CREATE TABLE courses (
  id              TEXT PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
  workspace_id    TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  title           TEXT NOT NULL,
  description     TEXT,
  audience        TEXT,
  duration        TEXT,
  -- objectives, learner_outcomes, theme_design, hero_image, hero_settings,
  -- and landing_layout are all stored as JSON. They are document-shaped,
  -- vary in structure, and are always read/written as a whole unit — they
  -- do not benefit from normalisation and a JSON column avoids an EAV
  -- anti-pattern. Indexed via the lessons/objectives tables for any query
  -- that needs to filter by objective content.
  objectives      TEXT NOT NULL DEFAULT '[]',  -- JSON array
  learner_outcomes TEXT NOT NULL DEFAULT '[]', -- JSON array
  theme_id        TEXT,
  theme_design    TEXT NOT NULL DEFAULT '{}',  -- JSON object
  landing_layout  TEXT NOT NULL DEFAULT 'A',
  hero_image      TEXT NOT NULL DEFAULT '{}',  -- JSON object
  hero_settings   TEXT NOT NULL DEFAULT '{}',  -- JSON object
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);

CREATE INDEX idx_courses_workspace ON courses (workspace_id);


-- ===========================================================================
-- course_objectives
-- ===========================================================================
-- Normalised rows for each Bloom's-taxonomy learning objective so they can
-- be linked to lessons individually and queried without JSON parsing.
-- The ordering within a course is tracked via position (0-based integer).
CREATE TABLE course_objectives (
  id          TEXT PRIMARY KEY,
  course_id   TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  verb        TEXT NOT NULL,   -- Bloom's verb e.g. 'Identify', 'Explain'
  text        TEXT NOT NULL,   -- remainder of the objective statement
  position    INTEGER NOT NULL DEFAULT 0,
  created_at  INTEGER NOT NULL
);

CREATE INDEX idx_course_objectives_course ON course_objectives (course_id);


-- ===========================================================================
-- lessons
-- ===========================================================================
-- One row per lesson within a course. Content (blocks) is stored as a JSON
-- column rather than a blocks table — blocks are always loaded and saved as
-- a whole array and never queried individually by the application, making a
-- flat JSON column significantly faster and simpler than a per-block table.
CREATE TABLE lessons (
  id            TEXT PRIMARY KEY,
  course_id     TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  title         TEXT NOT NULL,
  position      INTEGER NOT NULL DEFAULT 0,
  duration      TEXT,
  -- Full block array serialised as JSON. The application reads and writes
  -- this as a unit. Individual block IDs are stable (blk_xxx prefix) and
  -- are embedded within the JSON — they are not separately indexed because
  -- no query needs to locate a single block across lessons.
  blocks        TEXT NOT NULL DEFAULT '[]', -- JSON array of block objects
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL
);

CREATE INDEX idx_lessons_course    ON lessons (course_id);
CREATE INDEX idx_lessons_workspace ON lessons (workspace_id);


-- ===========================================================================
-- lesson_objective_links
-- ===========================================================================
-- Many-to-many: a lesson can address multiple objectives; an objective can
-- be addressed by multiple lessons. Replaces the prototype's
-- lesson.objectiveIndex (single integer) with a proper join table.
CREATE TABLE lesson_objective_links (
  lesson_id     TEXT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  objective_id  TEXT NOT NULL REFERENCES course_objectives(id) ON DELETE CASCADE,
  PRIMARY KEY (lesson_id, objective_id)
);

CREATE INDEX idx_lesson_objective_links_objective
  ON lesson_objective_links (objective_id);


-- ===========================================================================
-- assessments
-- ===========================================================================
-- One row per assessment (Quiz) within a course. Questions are embedded
-- as JSON (same rationale as lesson blocks — always read/written as a unit).
CREATE TABLE assessments (
  id            TEXT PRIMARY KEY,
  course_id     TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  title         TEXT NOT NULL,
  type          TEXT NOT NULL DEFAULT 'Quiz'
                  CHECK (type IN ('Quiz', 'Survey')),
  -- objectives covered by this assessment (JSON array of objective ids)
  objective_ids TEXT NOT NULL DEFAULT '[]',
  -- question blocks serialised as JSON (same structure as lesson blocks)
  blocks        TEXT NOT NULL DEFAULT '[]',
  pass_score    INTEGER NOT NULL DEFAULT 80
                  CHECK (pass_score BETWEEN 0 AND 100),
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL
);

CREATE INDEX idx_assessments_course    ON assessments (course_id);
CREATE INDEX idx_assessments_workspace ON assessments (workspace_id);


-- ===========================================================================
-- assets
-- ===========================================================================
-- Every uploaded media file — images, audio, video, PDFs, attachments.
-- The actual bytes live in R2; this table holds the metadata needed to
-- construct the R2 object key, serve the asset, and manage storage quotas.
--
-- R2 object key follows the hierarchy:
--   {workspace_id}/{course_id}/{asset_id}.{ext}
-- for course-scoped assets, or:
--   {workspace_id}/users/{user_id}/{asset_id}.{ext}
-- for user avatars. The full key is stored in r2_key so it can be
-- reconstructed without re-deriving the hierarchy.
CREATE TABLE assets (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  -- Nullable: NULL for workspace-level assets (e.g. user avatars). Set for
  -- course-scoped media so assets cascade-delete with their course.
  course_id     TEXT REFERENCES courses(id) ON DELETE CASCADE,
  uploaded_by   TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  file_name     TEXT NOT NULL,
  mime_type     TEXT NOT NULL,
  size_bytes    INTEGER NOT NULL CHECK (size_bytes > 0),
  r2_key        TEXT NOT NULL UNIQUE,
  -- width/height are nullable — only meaningful for image assets.
  width_px      INTEGER,
  height_px     INTEGER,
  created_at    INTEGER NOT NULL,
  deleted_at    INTEGER
);

CREATE INDEX idx_assets_workspace  ON assets (workspace_id);
CREATE INDEX idx_assets_course     ON assets (course_id) WHERE course_id IS NOT NULL;
CREATE INDEX idx_assets_uploader   ON assets (uploaded_by);
CREATE INDEX idx_assets_active     ON assets (workspace_id) WHERE deleted_at IS NULL;


-- ===========================================================================
-- reviews
-- ===========================================================================
-- Append-only governance audit trail — one row per governance action on a
-- project (submitted, approved, rejected, published, republished, archived,
-- restored). Replaces the prototype's project.reviewHistory JSON array
-- with a proper indexed table.
CREATE TABLE reviews (
  id          TEXT PRIMARY KEY,
  project_id  TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  actor_id    TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  action      TEXT NOT NULL
                CHECK (action IN ('submit_for_review', 'approve', 'reject',
                                  'publish', 'republish', 'archive', 'restore')),
  comment     TEXT,  -- mandatory for 'reject'; optional for all others
  created_at  INTEGER NOT NULL
);

CREATE INDEX idx_reviews_project ON reviews (project_id);
CREATE INDEX idx_reviews_actor   ON reviews (actor_id);


-- ===========================================================================
-- invitations
-- ===========================================================================
-- Workspace invitations — extends 0001's auth tables. Each row records a
-- pending (or consumed) invitation to join a specific workspace.
CREATE TABLE invitations (
  id                    TEXT PRIMARY KEY,
  workspace_id          TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  invited_by            TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  email                 TEXT NOT NULL
                          CHECK (email = lower(trim(email))),
  first_name            TEXT NOT NULL,
  last_name             TEXT NOT NULL DEFAULT '',
  role                  TEXT NOT NULL DEFAULT 'administrator'
                          CHECK (role IN ('workspace_owner', 'administrator')),
  auth_provider         TEXT NOT NULL DEFAULT 'email'
                          CHECK (auth_provider IN ('email', 'google',
                                                   'microsoft', 'apple')),
  -- Stored as a hash (same pattern as sessions.refresh_token_hash).
  token_hash            TEXT NOT NULL UNIQUE,
  status                TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'accepted', 'revoked', 'expired')),
  expires_at            INTEGER NOT NULL,
  accepted_at           INTEGER,
  -- The user account created or linked at acceptance time.
  accepted_by_user_id   TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at            INTEGER NOT NULL
);

CREATE INDEX idx_invitations_workspace ON invitations (workspace_id);
CREATE INDEX idx_invitations_email     ON invitations (email);
CREATE INDEX idx_invitations_pending
  ON invitations (workspace_id) WHERE status = 'pending';


-- ===========================================================================
-- notifications
-- ===========================================================================
-- Per-user in-platform notification ledger. Append-only; rows are never
-- updated except to set read_at. Replaces the prototype's flat
-- LumioState.notifications array.
CREATE TABLE notifications (
  id          TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Optional reference to the project this notification concerns.
  project_id  TEXT REFERENCES projects(id) ON DELETE SET NULL,
  type        TEXT NOT NULL DEFAULT 'review'
                CHECK (type IN ('review', 'system', 'ai', 'export', 'publish')),
  message     TEXT NOT NULL,
  detail      TEXT,
  icon        TEXT,
  -- dest is a JSON object { route, courseId?, openPublish? } used by the
  -- frontend to navigate on click — kept as JSON since its shape varies
  -- by notification type and is never queried.
  dest        TEXT,    -- JSON
  read_at     INTEGER, -- NULL = unread
  created_at  INTEGER NOT NULL
);

CREATE INDEX idx_notifications_user        ON notifications (user_id);
CREATE INDEX idx_notifications_user_unread
  ON notifications (user_id) WHERE read_at IS NULL;


-- ===========================================================================
-- audit_log
-- ===========================================================================
-- Immutable, append-only record of every significant state-changing
-- operation in the system. Used for compliance, debugging, and support.
-- Rows are never updated or deleted.
CREATE TABLE audit_log (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT,   -- NULL for system-level events
  actor_id      TEXT,   -- NULL for automated/system actions
  -- event is a dotted-namespace string: 'user.registered', 'project.published',
  -- 'workspace.member.invited', etc. Not a FK/enum — new event types are added
  -- by the application without a schema migration.
  event         TEXT NOT NULL,
  -- target_type / target_id identify the primary resource the event concerns.
  target_type   TEXT,   -- e.g. 'project', 'user', 'invitation'
  target_id     TEXT,
  -- metadata holds any supplementary context as JSON — old/new values for
  -- changes, IP address, user agent, etc. Never queried for content; only
  -- ever fetched as a blob for display in an audit UI or support tools.
  metadata      TEXT,   -- JSON
  created_at    INTEGER NOT NULL
);

CREATE INDEX idx_audit_log_workspace ON audit_log (workspace_id)
  WHERE workspace_id IS NOT NULL;
CREATE INDEX idx_audit_log_actor     ON audit_log (actor_id)
  WHERE actor_id IS NOT NULL;
CREATE INDEX idx_audit_log_target    ON audit_log (target_type, target_id)
  WHERE target_type IS NOT NULL;
CREATE INDEX idx_audit_log_event     ON audit_log (event, created_at);


-- ===========================================================================
-- learner_progress
-- ===========================================================================
-- Per-learner, per-course progress record. In the prototype this lived in
-- LumioState.learnerProgress; here it is a proper table so progress
-- survives across devices and is queryable for analytics.
CREATE TABLE learner_progress (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  course_id           TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  workspace_id        TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  status              TEXT NOT NULL DEFAULT 'not_started'
                        CHECK (status IN ('not_started', 'in_progress', 'completed')),
  score               INTEGER CHECK (score BETWEEN 0 AND 100),
  -- completed_lessons is a JSON array of lesson IDs — not normalised because
  -- the ordering and timestamp of each completion is in learner_lesson_progress.
  completed_lessons   TEXT NOT NULL DEFAULT '[]',
  last_lesson_id      TEXT REFERENCES lessons(id) ON DELETE SET NULL,
  last_block_index    INTEGER,
  last_accessed_at    INTEGER,
  completed_at        INTEGER,
  created_at          INTEGER NOT NULL,
  updated_at          INTEGER NOT NULL,
  UNIQUE (user_id, course_id)
);

CREATE INDEX idx_learner_progress_user     ON learner_progress (user_id);
CREATE INDEX idx_learner_progress_course   ON learner_progress (course_id);
CREATE INDEX idx_learner_progress_workspace ON learner_progress (workspace_id);


-- ===========================================================================
-- learner_interactions
-- ===========================================================================
-- Append-only knowledge-check interaction ledger. Each row is one attempt
-- at one knowledge-check block. Replaces the prototype's
-- LumioState.interactionHistory nested object.
CREATE TABLE learner_interactions (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  course_id       TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  lesson_id       TEXT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  block_id        TEXT NOT NULL,  -- stable blk_xxx id within the lesson
  attempt_number  INTEGER NOT NULL DEFAULT 1,
  interaction_type TEXT NOT NULL, -- 'multiple_choice', 'matching', etc.
  learner_response TEXT,          -- JSON
  correct_response TEXT,          -- JSON
  result          TEXT NOT NULL
                    CHECK (result IN ('correct', 'incorrect', 'partial')),
  score_raw       INTEGER,
  score_max       INTEGER,
  created_at      INTEGER NOT NULL
);

CREATE INDEX idx_learner_interactions_user   ON learner_interactions (user_id);
CREATE INDEX idx_learner_interactions_course ON learner_interactions (course_id);
CREATE INDEX idx_learner_interactions_lesson ON learner_interactions (lesson_id);
